name: Testing

on: [push]

jobs:
  # run-backend-tests:
  #   name: Backend tests
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions/setup-node@v1
  #     with:
  #       node-version: 12
  #   - uses: shivammathur/setup-php@v2
  #     with:
  #       php-version: 7.3
  #   - name: Copy .env
  #     run: cp .env.testing .env
  #   - name: Create Database
  #     run: |
  #         sudo systemctl start mysql
  #         mysql --user="root" --password="root" -e "CREATE DATABASE cypress character set UTF8mb4 collate utf8mb4_bin;"
  #         mysql --user="root" --password="root" -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'";
  #   - name: Install Composer Dependencies
  #     run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
  #   - name: Generate key
  #     run: php artisan key:generate
  #   - name: Run Laravel Server
  #     run: php artisan serve > /dev/null 2>&1 &
  #   - name: Install Node Dependencies
  #     run: npm ci
  #   - name: Build assets
  #     run: npm run production
  #   - name: Execute tests
  #     run: npm run cy:run
  run-frontend-tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16.13.1
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
    - name: Copy .env
      run: cp .env.testing .env
    - name: Create Database
      run: |
          sudo systemctl start mysql
          mysql --user="root" --password="root" -e "CREATE DATABASE cypress character set UTF8mb4 collate utf8mb4_bin;"
          mysql --user="root" --password="root" -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'";
    - name: Install Composer Dependencies
      run: composer install --no-scripts
    - name: Generate key
      run: php artisan key:generate
    - name: Run Laravel Server
      run: php artisan serve > /dev/null 2>&1 &
    - name: Curl
      run: curl http://127.0.0.1:8000
    - name: Copy Frontend .env
      run: cp frontend/.env.testing frontend/.env
    - name: Install Node Dependencies
      run: cd frontend && npm install
    - name: Execute tests
      run: cd frontend && npm run cy:test
